# SPDX-FileCopyrightText: 2023 Alejandro AR
# SPDX-FileCopyrightText: 2023-2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure n8n paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ n8n_uid }}"
    group: "{{ n8n_gid }}"
  with_items:
    - "{{ n8n_base_path }}"
    - "{{ n8n_data_path }}"
    - "{{ n8n_config_path }}"

- name: Ensure n8n support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ n8n_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ n8n_uid }}"
    group: "{{ n8n_gid }}"
  with_items:
    - env
    - labels
  register: n8n_support_files_result

- name: Ensure n8n container image is pulled via community.docker.docker_image
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image:
    name: "{{ n8n_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ n8n_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else n8n_container_image_force_pull }}"
  register: n8n_container_image_pull_result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: n8n_container_image_pull_result is not failed

- name: Ensure n8n container image is pulled via ansible.builtin.command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ n8n_container_image }}"
  register: n8n_container_image_pull_result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: n8n_container_image_pull_result is not failed
  changed_when: "'Downloaded newer image' in n8n_container_image_pull_result.stdout"

- name: Ensure n8n container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ n8n_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"
  register: n8n_network_creation_result

- name: Ensure n8n container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ n8n_container_network }}
  register: n8n_network_creation_result
  changed_when: n8n_network_creation_result.rc == 0
  failed_when: n8n_network_creation_result.rc != 0 and 'already exists' not in n8n_network_creation_result.stderr

- name: Ensure n8n systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/n8n.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ n8n_identifier }}.service"
    mode: "0644"
  register: n8n_systemd_service_result

- name: Determine whether n8n needs a restart
  ansible.builtin.set_fact:
    n8n_restart_necessary: >-
      {{
        n8n_support_files_result.changed | default(false)
        or n8n_systemd_service_result.changed | default(false)
        or n8n_container_image_pull_result.changed | default(false)
      }}
