# SPDX-FileCopyrightText: 2023 Alejandro AR
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform n8n installation tasks
  when: n8n_enabled | bool
  tags:
    - setup-all
    - setup-n8n
    - install-all
    - install-n8n
  block:
    - name: Validate n8n configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install n8n
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform n8n uninstallation tasks
  when: not n8n_enabled | bool
  tags:
    - setup-all
    - setup-n8n
  block:
    - name: Uninstall n8n
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
