# SPDX-FileCopyrightText: 2023 Alejandro AR
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of n8n systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ n8n_identifier }}.service"
  register: n8n_service_stat

- name: Uninstall n8n systemd services and files
  when: n8n_service_stat.stat.exists | bool
  block:
    - name: Ensure n8n systemd service is stopped
      ansible.builtin.service:
        name: "{{ n8n_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure n8n systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ n8n_identifier }}.service"
        state: absent

    - name: Ensure n8n support files do not exist
      ansible.builtin.file:
        path: "{{ n8n_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure n8n local config path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ n8n_config_path }}"
      register: n8n_config_path_deletion_result
      changed_when: n8n_config_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure n8n local data path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ n8n_data_path }}"
      register: n8n_data_path_deletion_result
      changed_when: n8n_data_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure n8n base path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ n8n_base_path }}"
      register: n8n_base_path_deletion_result
      changed_when: n8n_base_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure n8n container network does not exist
      when: n8n_container_network_deletion_enabled
      block:
        - name: Ensure n8n container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ n8n_container_network }}"
            state: absent
          register: n8n_network_deletion_result

        - name: Ensure n8n container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ n8n_container_network }}
          register: n8n_network_deletion_result
          changed_when: n8n_container_network in n8n_network_deletion_result.stdout

- name: Check existence of n8n local config path
  ansible.builtin.stat:
    path: "{{ n8n_config_path }}"
  register: n8n_config_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if n8n local config remains
  when: n8n_config_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local n8n instance has been removed, some old config data remains in `" + n8n_config_path + "`. Feel free to delete it."
        ]
      }}

- name: Check existence of n8n local data path
  ansible.builtin.stat:
    path: "{{ n8n_data_path }}"
  register: n8n_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if n8n local data remains
  when: n8n_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local n8n instance has been removed, some old data remains in `" + n8n_data_path + "`. Feel free to delete it."
        ]
      }}
