# SPDX-FileCopyrightText: 2023 Alejandro AR
# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2023-2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required n8n settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and lookup('vars', item.name, default='') | string | length == 0"
  with_items:
    - { "name": "n8n_uid", when: true }
    - { "name": "n8n_gid", when: true }
    - { "name": "n8n_hostname", when: true }
    - { "name": "n8n_path_prefix", when: true }
    - { "name": "n8n_container_network", when: true }
    - { "name": "n8n_database_socket_path_host", when: "{{ n8n_database_socket_enabled }}" }
    - { "name": "n8n_database_hostname", when: "{{ not n8n_database_socket_enabled }}" }
    - { "name": "n8n_database_password", when: true }

- name: Run if Traefik is enabled
  when: n8n_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for n8n are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - n8n_container_labels_traefik_hostname
        - n8n_container_labels_traefik_path_prefix

    - name: Fail if n8n_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          n8n_container_labels_traefik_path_prefix (`{{ n8n_container_labels_traefik_path_prefix }}`) must be `/`.
          n8n does not support hosting under a subpath yet.
      when: "n8n_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `n8n_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if n8n_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          n8n_container_labels_traefik_path_prefix (`{{ n8n_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/n8n`).
      when: "n8n_container_labels_traefik_path_prefix != '/' and n8n_container_labels_traefik_path_prefix[-1] == '/'"
